#!/usr/bin/env python3
"""Rust backends against Neo4j over Bolt, from the site's published strain
evidence, as Markdown. Uses the strain page's own loader, pairing and reach
functions (render-strain-summary.py) so the two cannot disagree.

    scripts/render-rust-vs-neo4j.py --site ~/src/adversarial-site [-o rust-vs-neo4j.md]
"""
import argparse
import collections
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("strain", os.path.join(HERE, "render-strain-summary.py"))
S = importlib.util.module_from_spec(spec)
spec.loader.exec_module(S)

REF = "neo4j"
SLICE = S.SLICE_LABEL


def md_escape(s):
    return str(s).replace("|", "\\|")


def verdict(v):
    if v["pairs"] < 2:
        return "one pair"
    if v["wins"] == v["pairs"]:
        return "always faster"
    if v["wins"] == 0:
        return "never faster"
    return "mixed"


def render(site):
    evidence = os.path.join(site, "public", "evidence", "strain")
    runs, cells, pubs, history = S.load(evidence)
    sizes, _nodes, _hub = S.dataset_sizes(cells)
    R, untyped = S.reach(cells, sizes)
    h2h, order = S.head_to_head(cells, REF)
    label = {(sc, m): lab for sc, m, lab in order}
    name = lambda b: S.BACKENDS[b]["name"]
    ref_name = name(REF)
    CL = lambda b: sizes.get(R[b]["clean"], 0)
    rust = [b for b in S.RUST if any(k[0] == b for k in h2h)]
    rust_rank = sorted(rust, key=lambda b: (CL(b), R[b]["n_clean"]), reverse=True)

    always = collections.defaultdict(list)
    for (b, sc, m), v in h2h.items():
        if v["pairs"] >= 2 and v["wins"] == v["pairs"]:
            always[b].append((sc, m, v))
    n_always = {b: len(v) for b, v in always.items()}
    n_metrics_paired = {b: sum(1 for k in h2h if k[0] == b) for b in rust}
    n_never = {b: sum(1 for k, v in h2h.items() if k[0] == b and v["pairs"] >= 2 and v["wins"] == 0) for b in rust}
    total_pairs = sum(v["pairs"] for v in h2h.values())

    out = []
    w = out.append
    w("# Rust against Neo4j in the strain benchmark\n")
    w(f"Computed from the site's published strain evidence: {len(pubs)} verified publications, "
      f"{pubs[0][:10]} to {pubs[-1][:10]}, {len(runs)} runs, {len(cells):,} current cells "
      f"({len(history):,} superseded cells are excluded). Generated by `scripts/render-rust-vs-neo4j.py` "
      f"with the strain page's own functions (`scripts/render-strain-summary.py`), so the two agree.\n")

    # ---- the short answer
    w("## The short answer\n")
    speed_leaders = [b for b in rust_rank if n_always.get(b)]
    w(f"Across {total_pairs} same-machine pairs, {len(speed_leaders)} of the {len(rust)} Rust backends with pairs "
      f"beat {ref_name} in every pair on at least one metric; {ref_name} reaches the largest whole graph clean on all "
      f"four core families ({R[REF]['clean']}, {S.edges(CL(REF))} edges), and "
      + (f"{name(rust_rank[0])} matches it." if CL(rust_rank[0]) == CL(REF) else
         f"the best Rust store, {name(rust_rank[0])}, is clean up to {R[rust_rank[0]]['clean']} ({S.edges(CL(rust_rank[0]))}).")
      + "\n")
    for b in rust_rank:
        if not always.get(b):
            continue
        items = "; ".join(f"{label[(sc, m)]} ({v['wins']}/{v['pairs']}, median {v['median']:.1f}× faster)"
                          for sc, m, v in sorted(always[b], key=lambda x: order.index((x[0], x[1], label[(x[0], x[1])]))))
        w(f"- **{name(b)}** is faster than {ref_name} every time at: {items}.")
    for b in rust_rank:
        nm, na, nn = n_metrics_paired[b], n_always.get(b, 0), n_never[b]
        if na == 0:
            w(f"- **{name(b)}** beats {ref_name} in every pair on none of its {nm} paired metrics"
              + (f"; it is slower in every pair on {nn} of them." if nn else "."))
    w(f"- **Reach.** {ref_name} is clean, all four core families (A1, A2, A4, A12) passing, on every whole untyped graph up to "
      f"{R[REF]['clean']} ({S.edges(CL(REF))} edges)."
      + ("" if not R[REF]["first_wall"] else f" Its first wall is {R[REF]['first_wall']}."))
    for b in rust_rank[:4]:
        fur = R[b]["sustained"] if sizes.get(R[b]["sustained"], 0) > CL(b) else None
        w(f"- **{name(b)}** is clean up to {R[b]['clean']} ({S.edges(CL(b))})"
          + (f"; it also loads {fur} ({S.edges(sizes[fur])}) and passes every family it ran there, but not all four ran, so that graph does not count as clean." if fur else ".")
          + (f" First wall: {R[b]['first_wall']} ({S.CAUSE[R[b]['status'][R[b]['first_wall']]['cause']][1]})." if R[b]["first_wall"] else ""))
    servers = [b for b in rust if S.BACKENDS[b]["group"] == "rust-server"]
    if servers:
        graphs = sorted({d for b in servers for k in h2h if k[0] == b for d, *_ in h2h[k]["detail"]}, key=sizes.get)
        w(f"- **The Rust servers** ({', '.join(name(b) for b in servers)}) have pairs only on "
          f"{', '.join(graphs)}, because they do not load larger graphs under the standard envelope; each is clean up to "
          f"{S.edges(max(CL(b) for b in servers))} edges.")
    w("")

    # ---- method
    w("## How the comparison was made\n")
    w(f"- **A pair** is one Rust backend and {ref_name} that both **passed** the same scenario on the same graph, the same "
      "edge slice and the same machine (the same host and CPU count), under the standard configuration (6 GiB containers, "
      "each store's defaults). Rows from different machines are never compared.")
    w("- **Faster** compares the metric below; the ratio is Neo4j's value over the Rust store's, so above 1 means the Rust store was faster.")
    w("- **Always faster** means the Rust store won every pair, with at least two pairs; **never faster** means it won none, with at least two.")
    w("- **Metrics:** loading (wall time to load the graph), A1 hub fan-out (k-hop layers from the highest-degree vertex), "
      "A2 deep walk (hop-by-hop reach on a high-diameter graph), A4 (a hundred concurrent writers attaching edges to one hub), "
      "A12 cold start (fresh handle to first correct answer) and A12 p99 response time of an open-loop read stream at 200 requests per second.")
    w("- **Not compared:** memory footprint. A server reports its container's memory; an embedded store's only figure is the "
      "whole harness process, reference graph included, so the two are not the same measurement.\n")

    # ---- head to head table
    w("## Head to head, by Rust backend and metric\n")
    w("| Rust backend | " + " | ".join(lab for _, _, lab in order) + " |")
    w("|---|" + "---|" * len(order))
    for b in rust_rank:
        cells_ = []
        for sc, m, _lab in order:
            v = h2h.get((b, sc, m))
            cells_.append("–" if not v else f"{verdict(v)} · {v['wins']}/{v['pairs']} · {S.ratio(v['median'])}")
        w(f"| {name(b)} | " + " | ".join(cells_) + " |")
    w("\nEach cell: verdict · pairs won / pairs · median ratio (Neo4j ÷ Rust).\n")

    # ---- reach
    w("## Reach and correctness\n")
    w("Standard envelope, whole untyped graphs. *Largest clean*: the biggest graph loaded with all four core families "
      "passing. *Further*: a larger graph loaded where every family that ran passed, but not all four ran.\n")
    w("| Backend | Built as | Largest clean | Further | Largest loaded | First wall | Gated failures |")
    w("|---|---|---|---|---|---|---|")
    for b in rust_rank + [REF, "neo4j-http"]:
        r = R[b]
        fur = r["sustained"] if sizes.get(r["sustained"], 0) > CL(b) else None
        wall = r["first_wall"]
        w(f"| {name(b)} | {S.BACKENDS[b]['lang']}, {S.BACKENDS[b]['form']} | "
          f"{(r['clean'] + ' (' + S.edges(CL(b)) + ')') if r['clean'] else '–'} | "
          f"{(fur + ' (' + S.edges(sizes[fur]) + ')') if fur else 'same'} | "
          f"{(r['loaded'] + ' (' + S.edges(sizes[r['loaded']]) + ')') if r['loaded'] else '–'} | "
          f"{(wall + ' (' + S.CAUSE[r['status'][wall]['cause']][1] + ')') if wall else 'none'} | "
          f"{', '.join(r['wrong']) or 'none'} |")
    gated = collections.defaultdict(list)
    typed = sorted((d for d in sizes if d in S.DATASETS and S.DATASETS[d][1]), key=sizes.get)
    for b in rust_rank + [REF, "neo4j-http"]:
        for d in untyped + typed:
            st = S.status(cells, b, d, S.DEFAULT)
            for f in st.get("bad", []):
                c = st["fams"][f]
                hit = ", ".join(f"{g} = {n}" for g, n in (c["row"].get("gates") or {}).items() if n)
                note = md_escape(" | ".join(c["row"].get("notes") or []))
                gated[c["cause"]].append(f"{name(b)}, {d}, {f}: {hit}" + (f" ({note})" if note else ""))
    if gated:
        w("\nGated failures on whole graphs, by kind:\n")
        for cause, items in gated.items():
            w(f"- **{S.CAUSE[cause][1][0].upper() + S.CAUSE[cause][1][1:]}:**")
            for it in items:
                w(f"  - {it}")
    w("")

    # ---- caveats
    w("## Caveats\n")
    w("- **In process against over the network.** grust-memory, Turso and LanceDB answer inside the harness process with no "
      "network hop and no serialization. Neo4j answers over Bolt from a container. Part of every in-process difference is that architecture, not the language.")
    w("- **Embedded stores are not in the 6 GiB container.** They are bounded by the host's memory guard, so a reach "
      "comparison between an embedded store and a containerized server is not memory for memory.")
    w("- **Different access paths.** The Rust stores are driven through Grust adapters; Neo4j through the harness's own Cypher over Bolt.")
    w("- **Few pairs for the servers.** SurrealDB and HelixDB are comparable only on the smallest graphs.")
    w("- **A4 is not the same work everywhere.** Turso's WAL journal refuses most concurrent writes with typed conflicts by "
      "design, so its A4 time covers fewer applied writes than Neo4j's; Turso's MVCC journal accepts them all.")
    w("- **Profiles.** Pairs use each store's harness-default profile only. Turso MVCC rows taken at `synchronous = NORMAL` "
      "are not default and are not paired, so every hot-node-write pair compares durable commits on both sides.")
    w("- **One current cell per graph and store.** The page keeps the newest default-profile run of each cell regardless of "
      "machine, so a pair exists only where both stores' current cells are on the same machine; pairs from earlier runs on "
      "other machines are in the page's history, not here.\n")

    # ---- every pair
    w("## Every pair\n")
    for b in rust_rank:
        w(f"### {name(b)}\n")
        w("| Metric | Graph | Slice | Machine | Rust | Neo4j | Neo4j ÷ Rust |")
        w("|---|---|---|---|---|---|---|")
        for sc, m, lab in order:
            v = h2h.get((b, sc, m))
            if not v:
                continue
            fmt = (lambda x: f"{x:.1f} ms") if m == "cold_start_ms" else S.dur
            for ds, sl, host, rv, nv in v["detail"]:
                w(f"| {lab} | {ds} | {SLICE.get(sl, sl)} | {host} | {fmt(rv)} | {fmt(nv)} | {S.ratio(nv / rv)} |")
        w("")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--site", default=os.path.expanduser("~/src/adversarial-site"))
    ap.add_argument("-o", "--out", default=os.path.join(HERE, "..", "rust-vs-neo4j.md"))
    a = ap.parse_args()
    text = render(a.site)
    with open(a.out, "w") as f:
        f.write(text)
    print(f"wrote {os.path.normpath(a.out)} ({len(text):,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
